"""Initial migrations

Revision ID: 0dc0de3fe103
Revises: 
Create Date: 2026-04-19 11:12:32.785202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR
import os

load_dotenv = os.getenv('LOAD_DOTENV', 'true').lower() == 'true'

# revision identifiers, used by Alembic.
revision: str = '0dc0de3fe103'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create pgvector extension first
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interactions_item_id', 'interactions', ['item_id'], unique=False)
    op.create_index('idx_interactions_user_created', 'interactions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_interactions_user_id', 'interactions', ['user_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embeddings', VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_items_category', 'items', ['category'], unique=False)
    op.create_index('idx_items_embeddings', 'items', ['embeddings'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embeddings': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    op.create_index('idx_items_tags', 'items', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('recommendation_cache',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_ids', sa.JSON(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('recommendation_cache')
    op.drop_index('idx_items_tags', table_name='items', postgresql_using='gin')
    op.drop_index('idx_items_embeddings', table_name='items', postgresql_using='ivfflat', postgresql_ops={'embeddings': 'vector_cosine_ops'}, postgresql_with={'lists': 100, 'probes': 10})
    op.drop_index('idx_items_category', table_name='items')
    op.drop_table('items')
    op.drop_index('idx_interactions_user_id', table_name='interactions')
    op.drop_index('idx_interactions_user_created', table_name='interactions')
    op.drop_index('idx_interactions_item_id', table_name='interactions')
    op.drop_table('interactions')
    # ### end Alembic commands ###
